# Generated by Django 6.1 on 2026-09-07 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1650.00'), max_digits=12),
        ),
    ]
