# Generated by Django 6.1 on 2026-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_available_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Designates whether the user has accepted Terms & Conditions and Privacy Policy.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when Terms & Conditions and Privacy Policy were accepted.', null=True),
        ),
    ]
