# Generated by Django 6.1 on 2026-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='colours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='preference',
            name='hobbies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='preference',
            name='stores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='preference',
            name='styles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
